---

- name: "remove old mozilla apt repository"
  file:
    path: "/etc/apt/sources.list.d/packages_mozilla_org_apt.list"
    state: "absent"
  tags:
  - "mozilla"
  - "browser"
  - "networking"

- name: "remove tftp (replaced by atftp) via apt"
  apt:
    pkg:
    - "tftp"
    state: "absent"
  when: ansible_distribution_major_version == "13"
  tags:
  - "networking"