---

- name: "install useful networking tools via apt"
  apt:
    pkg:
    - "curl"
    - "lynx"
    - "net-tools"
    - "sshfs"
    - "tftp"
    - "sshuttle"
    - "traceroute"
    - "whois"
    state: "present"
  tags:
  - "networking"

# Install select browsers

- name: "add the mozilla signing key"
  apt_key:
    url: "https://packages.mozilla.org/apt/repo-signing-key.gpg"
    id: "35BAA0B33E9EB396F59CA838C0BA5CE6DC6315A3"
    keyring: "{{ mozilla_apt_keyring }}"
  tags:
  - "mozilla"
  - "browser"
  - "networking"

- name: "add the mozilla apt repository"
  apt_repository: 
    repo: "{{ item }}"
  with_items:
  - "deb [ signed-by={{ mozilla_apt_keyring }} ] https://packages.mozilla.org/apt mozilla main"
  - "deb-src [ signed-by={{ mozilla_apt_keyring }} ] https://packages.mozilla.org/apt mozilla main"
  tags:
  - "mozilla"
  - "browser"
  - "networking"

- name: "add browsers of choice"
  apt:
    pkg:
    - "chromium"
    - "firefox-devedition"
    - "lynx"
  tags:
  - "browser"
  - "networking"

# Install VPN clients

- name: "install OpenVPN client"
  apt:
    pkg:
    - openvpn
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    state: present
  tags:
  - openvpn
  - vpn
  - networking

- name: "install OpenConnect VPN client"
  apt:
    pkg:
    - openconnect
    - network-manager-openconnect
    - network-manager-openconnect-gnome
    - vpnc-scripts
    state: present
  tags:
  - openconnect
  - vpn
  - networking

- name: "install L2TP VPN client"
  apt:
    pkg:
    - network-manager-l2tp
    - network-manager-l2tp-gnome
    state: present
  tags:
  - l2tp
  - vpn
  - networking

# Apache Directory Studio

- name: "Install Apache Directory Studio via flatpak"
  community.general.flatpak:
    name: "org.apache.directory.studio"
  tags:
    - "apache_directory_studio"
    - "ldap"
    - "networking"
