---

- name: "install useful networking tools via apt"
  apt:
    pkg:
    - "curl"
    - "lynx"
    - "net-tools"
    - "sshfs"
    - "tftp"
    - "sshuttle"
    - "tcpdump"
    - "traceroute"
    - "whois"
    state: "present"
  tags:
  - "networking"

# Install select browsers

- name: "add the mozilla apt repository"
  ansible.builtin.deb822_repository:
    name: mozilla
    types: deb
    uris: https://packages.mozilla.org/apt
    suites: mozilla
    components: main
    architectures: amd64
    signed_by: https://packages.mozilla.org/apt/repo-signing-key.gpg
    enabled: "{{ 'yes' if ansible_distribution_release in ['bookworm', 'trixie'] else 'no' }}"
  tags:
  - "mozilla"
  - "browser"
  - "networking"

- name: "add browsers of choice"
  apt:
    pkg:
    - "chromium"
    - "firefox-devedition"
    - "lynx"
  tags:
  - "browser"
  - "networking"

# Install VPN clients

- name: "install OpenVPN client"
  apt:
    pkg:
    - openvpn
    - network-manager-openvpn
    - network-manager-openvpn-gnome
    state: present
  tags:
  - openvpn
  - vpn
  - networking

- name: "install OpenConnect VPN client"
  apt:
    pkg:
    - openconnect
    - network-manager-openconnect
    - network-manager-openconnect-gnome
    - vpnc-scripts
    state: present
  tags:
  - openconnect
  - vpn
  - networking

- name: "install L2TP VPN client"
  apt:
    pkg:
    - network-manager-l2tp
    - network-manager-l2tp-gnome
    state: present
  tags:
  - l2tp
  - vpn
  - networking

# Apache Directory Studio

- name: "Install Apache Directory Studio via flatpak"
  community.general.flatpak:
    name: "org.apache.directory.studio"
  tags:
    - "apache_directory_studio"
    - "ldap"
    - "networking"
