---
# File: roles/eclipse/tasks/main.yml
#
# See the following link for information on the p2.director application:
#
# - http://help.eclipse.org/indigo/index.jsp?topic=%2Forg.eclipse.platform.doc.isv%2Fguide%2Fp2_director.html
#

#
# Install Eclipse JEE/BIRT (version and release from variables)
#

- name: create a directory for optional Eclipse software
  file: name={{ eclipse_installation_directory }}
        state=directory
  tags:
    - eclipse

- name: download latest version of Eclipse JEE/BIRT (64-bit)
  uri: url={{ eclipse_url_64 }}
       dest=~/{{ eclipse_file_64 }}
       creates=~/{{ eclipse_file_64 }}
  when: ansible_architecture == "x86_64"
  tags:
    - eclipse

- name: download latest version of Eclipse JEE/BIRT (32-bit)
  uri: url={{ eclipse_url_32 }}
       dest=~/{{ eclipse_file_32 }}
       creates=~/{{ eclipse_file_32 }}
  when: ansible_architecture == "i386"
  tags:
    - eclipse

- name: untar the Eclipse JEE/BIRT archive (64-bit)
  unarchive: copy=no
             src=~/{{ eclipse_file_64 }}
             dest={{ eclipse_installation_directory }}
             creates={{ eclipse_home_directory }}
  when: ansible_architecture == "x86_64"
  register: unarchive_result_64
  tags:
    - eclipse

- name: untar the Eclipse JEE/BIRT archive (32-bit)
  unarchive: copy=no
             src=~/{{ eclipse_file_32 }}
             dest={{ eclipse_installation_directory }}
             creates={{ eclipse_home_directory }}
  when: ansible_architecture == "i386"
  register: unarchive_result_32
  tags:
    - eclipse

- name: move the tar file's base directory somewhere maintainable
  command: mv {{ eclipse_tar_directory }}
           {{ eclipse_home_directory }}
  when: (unarchive_result_64 is changed) or (unarchive_result_32 is changed)
  tags:
    - eclipse

- name: create a pretty symlink to the latest version
  file: src={{ eclipse_home_directory }}
        path={{ eclipse_installation_directory }}/latest
        state=link
  tags:
    - eclipse

- name: add a launcher to the development menu
  template: src=../files/eclipse.desktop
            dest=/usr/share/applications
  tags:
    - eclipse
    
- name: set the JVM arguments in eclipse.ini
  lineinfile: dest=/opt/eclipse/latest/eclipse.ini regexp={{ item.regexp }} line={{ item.line }} state=present
  with_items:
    - { "regexp":"^-Xms[0-9]+m$", "line":"-Xms256m" }
    - { "regexp":"^-Xmx[0-9]+m$", "line":"-Xmx2048m"}
  tags:
    - eclipse

- name: create a symlink for the latest version of eclipse
  file: src={{ eclipse_installation_directory }}/latest/eclipse
        path=/usr/bin/eclipse
        state=link
  tags:
    - eclipse

#
# Install Lombok
#

- name: download latest version of Lombok
  uri: url={{ lombok_url }}
       dest=~/{{ lombok_file }}
       creates=~/{{ lombok_file }}
  tags:
    - eclipse

- name: copy lombok into the Eclipse installation directory
  shell: cp ~/{{ lombok_file }} {{ eclipse_installation_directory }}/latest
         creates={{ eclipse_installation_directory }}/latest/{{ lombok_file }}
  tags:
    - eclipse

- name: add lombok as an Eclipse javaagent
  lineinfile: dest={{ eclipse_installation_directory }}/latest/eclipse.ini
              regexp="-javaagent:{{ eclipse_installation_directory }}/latest/lombok.*$"
              line="-javaagent:{{ eclipse_installation_directory }}/latest/{{ lombok_file }}"
              state=present
  tags:
    - lombok
    - eclipse

#
# Make it easier to deal with Eclipse Marketplace plugins
#

- name: install the Nodeclipse CLI Installer
  npm: name=nodeclipse global=yes state=present
  tags:
    - eclipse
    - eclipse-plugin
    
#
# Language support
#

- name: add Kotlin support
  command: nci install from https://dl.bintray.com/jetbrains/kotlin/eclipse-plugin/last/
                       org.jetbrains.kotlin.feature.feature.group
                       org.jetbrains.kotlin.policy.feature.group
                       org.jetbrains.kotlin.weaving.feature.feature.group
                       org.eclipse.equinox.weaving.sdk.feature.group
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/plugins/org.jetbrains.kotlin*
  tags:
    - eclipse
    - eclipse-plugin
    - kotlin

#
# SCM Plugin installation 
#

- name: add the EGit plugin
  command: nci install egit
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/plugins/org.eclipse.egit.core*
  tags:
    - eclipse
    - eclipse-plugin
    - git

- name: add the Subclipse plugin
  command: nci install from https://dl.bintray.com/subclipse/releases/subclipse/4.3.x/
                       com.collabnet.subversion.merge.feature.feature.group
                       net.java.dev.jna.feature.group
                       org.tigris.subversion.subclipse.feature.group
                       org.tigris.subversion.subclipse.mylyn.feature.group
                       org.tigris.subversion.clientadapter.feature.feature.group
                       org.tigris.subversion.clientadapter.javahl.feature.feature.group
                       org.tigris.subversion.subclipse.graph.feature.feature.group
                       org.tigris.subversion.clientadapter.svnkit.feature.feature.group
                       org.tmatesoft.svnkit.feature.group
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/plugins/org.tigris.subversion.subclipse.core*
  tags:
    - eclipse
    - eclipse-plugin
    - subversion

#- name: add the EGit - Mylyn interface
#  shell: >
#         /opt/eclipse/latest/eclipse
#         -noSplash
#         -application org.eclipse.equinox.p2.director
#         -repository http://download.eclipse.org/releases/luna
#         -profileProperties org.eclipse.update.install.features=true
#         -installIUs {{ item }}
#  with_items:
#    - org.eclipse.emf.sdk.feature.group
#    - org.eclipse.mylyn_feature.feature.group
#  tags:
#    - eclipse
#    - git

#
# Build plugin installation
#

- name: add the M2Eclipse plugin
  command: nci install from http://download.eclipse.org/technology/m2e/releases
                       org.eclipse.m2e.feature.feature.group
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/plugins/org.eclipse.m2e*
  tags:
    - eclipse
    - eclipse-plugin
    - maven

- name: add the BuildShip Gradle plugin
  command: nci install from http://download.eclipse.org/buildship/updates/e46/releases/1.0
                       org.eclipse.buildship.feature.group
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/plugins/org.eclipse.buildship.core*
  tags:
    - eclipse
    - eclipse-plugin
    - gradle

#
# Code quality and test coverage
#

- name: add the Checkstyle plugin
  command: nci install from http://eclipse-cs.sourceforge.net/update {{ item }}
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/plugins/eclipsecs-sevntu*
  with_items:
    - net.sf.eclipsecs.feature.group
    - com.github.sevntu.checkstyle.checks.feature.feature.group
  tags:
    - eclipse
    - eclipse-plugin
    - quality

- name: add the Findbugs plugin
  command: nci install from http://findbugs.cs.umd.edu/eclipse
                       edu.umd.cs.findbugs.plugin.eclipse.feature.group
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/plugins/edu.umd.cs.findbugs*
  tags:
    - eclipse
    - eclipse-plugin
    - quality

- name: add the EclEmma plugin
  command: nci install from http://update.eclemma.org
                       org.eclipse.eclemma.feature.feature.group
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/plugins/org.eclipse.eclemma.*
  tags:
    - eclipse
    - eclipse-plugin
    - coverage

- name: add the Pitclipse (Pitest) plugin
  command: nci install from http://eclipse.pitest.org/release/
                       org.pitest.pitclipse.feature.feature.group
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/features/org.pitest.*
  tags:
    - eclipse
    - eclipse-plugin
    - coverage
    - quality

- name: add the SonarLint plugin
  command: nci install from http://eclipse.sonarlint.org
                       org.sonarlint.eclipse.feature.feature.group
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/features/org.sonarlint.eclipse.*
  tags:
    - eclipse
    - eclipse-plugin
    - quality

- name: add the Infinitest plugin
  command: nci install from http://infinitest.github.com
                            org.infinitest.eclipse.feature.feature.group
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/features/org.infinitest.eclipse.*
  tags:
    - eclipse
    - eclipse-plugin
    - testing

#
# Extra text editors
#

- name: add the YAML Editor plugin
  command: nci install yaml
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/plugins/org.dadacoalition.yedit*
  tags:
    - eclipse
    - eclipse-plugin
    - editors
    - yaml

- name: add the Markdown Editor plugin
  command: nci install markdown
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/plugins/winterwell.markdown*
  tags:
    - eclipse
    - eclipse-plugin
    - editors
    - markdown

# TODO (smoyer1) - There are a lot of other cool tools in this repository
- name: add the JSON Editor plugin
  command: nci install from http://www.nodeclipse.org/updates
                       org.sweetlemonade.eclipse.json.feature.feature.group
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/plugins/org.sweetlemonade.eclipse.json*
  tags:
    - eclipse
    - eclipse-plugin
    - editors
    - json
  
#
# Issue tracking connectors
#

#- name: Atlassian - Mylyn connector requires additional Eclipse plugins (bundles)
#  shell: >
#         /opt/eclipse/luna/eclipse
#         -noSplash
#         -application org.eclipse.equinox.p2.director
#         -repository http://download.eclipse.org/tools/orbit/downloads/drops/R20140525021250/repository
#         -profileProperties org.eclipse.update.install.features=true
#         -installIUs {{ item }}
#         > /dev/null 2>&1 && echo $?
#         > /dev/null 2>&1 ; echo $?
#  with_items:
#    - javax.xml.soap
#    - org.apache.commons.io/2.0.1.v201105210651
#  tags:
#    - issues
#    
#- name: add Atlassian - Mylyn connector
#  shell: >
#         /opt/eclipse/luna/eclipse
#         -noSplash
#         -application org.eclipse.equinox.p2.director
#         -repository http://update.atlassian.com/atlassian-eclipse-plugin/rest/e3.7
#         -profileProperties org.eclipse.update.install.features=true
#         -installIUs {{ item }}
#  with_items:
#    - com.atlassian.connector.eclipse.feature.group
#  tags:
#    - issues
    
- name: add Github - Mylyn connector
  command: nci install from http://download.eclipse.org/egit/github/updates
                       org.eclipse.mylyn.github.feature.feature.group
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/plugins/org.eclipse.mylyn.github*
  tags:
    - eclipse
    - eclipse-plugin
    - mylyn
    - issues

#
# Framework plugins
#

# NOTE: (smoyer1) - Add Google plugins

#- name: install the JBoss Tools plugin
#  shell: >
#         /opt/eclipse/latest/eclipse
#         -noSplash
#         -application org.eclipse.equinox.p2.director
#         -repository http://download.jboss.org/jbosstools/updates/stable/luna
#         -profileProperties org.eclipse.update.install.features=true
#         -installIUs {{ item }}
#  with_items:
#    - org.jboss.tools.cdi.deltaspike.feature.feature.group
#    - org.jboss.tools.arquillian.feature.feature.group
#    - org.jboss.tools.cdi.feature.feature.group
#    - org.jboss.tools.forge.m2e.feature.feature.group
#    - org.jboss.tools.forge.feature.feature.group
#    - org.jboss.tools.forge.ext.feature.feature.group
#    - org.jboss.ide.eclipse.freemarker.feature.feature.group
#    - org.hibernate.eclipse.feature.feature.group
#    - org.jboss.ide.eclipse.archives.feature.feature.group
#    - org.jboss.tools.birt.feature.feature.group
#    - org.jboss.tools.central.themes.feature.feature.group
#    - org.jboss.tools.community.central.feature.feature.group
#    - org.jboss.tools.ws.jaxrs.feature.feature.group
#    - org.jboss.tools.maven.cdi.feature.feature.group
#    - org.jboss.tools.maven.jdt.feature.feature.group
#    - org.jboss.tools.maven.hibernate.feature.feature.group
#    - org.jboss.tools.maven.feature.feature.group
#    - org.jboss.tools.maven.portlet.feature.feature.group
#    - org.jboss.tools.maven.project.examples.feature.feature.group
#    - org.jboss.tools.maven.seam.feature.feature.group
#    - org.jboss.tools.openshift.express.feature.feature.group
#    - org.jboss.tools.portlet.feature.feature.group
#    - org.jboss.tools.runtime.core.feature.feature.group
#    - org.jboss.tools.runtime.seam.detector.feature.feature.group
#    - org.jboss.tools.stacks.core.feature.feature.group
#    - org.jboss.tools.vpe.cordovasim.feature.feature.group
#    - org.jboss.tools.wtp.runtimes.tomcat.feature.feature.group
#    - org.jboss.tools.common.mylyn.feature.feature.group
#    - org.jboss.tools.community.project.examples.feature.feature.group
#    - org.jboss.tools.aerogear.thym.feature.feature.group
#    - org.jboss.tools.openshift.egit.integration.feature.feature.group
#    - org.jboss.tools.foundation.feature.feature.group
#    - org.jboss.tools.foundation.security.linux.feature.feature.group
#    - org.jboss.tools.jst.feature.feature.group
#    - org.jboss.tools.jst.angularjs.feature.feature.group
#    - org.jboss.tools.jst.jsdt.feature.feature.group
#    - org.jboss.tools.common.jdt.feature.feature.group
#    - org.jboss.tools.jsf.feature.feature.group
#    - org.jboss.tools.livereload.feature.feature.group
#    - org.jboss.tools.maven.jbosspackaging.feature.feature.group
#    - org.jboss.tools.maven.sourcelookup.feature.feature.group
#    - org.jboss.tools.vpe.browsersim.feature.feature.group
#    - org.jboss.tools.richfaces.feature.feature.group
#    - org.jboss.tools.usage.feature.feature.group
#    - org.jboss.tools.vpe.feature.feature.group
#    - org.jboss.tools.ws.feature.feature.group
#    - org.jboss.ide.eclipse.as.feature.feature.group
#    - org.jboss.tools.jmx.feature.feature.group
#    - org.jboss.tools.maven.apt.feature.feature.group
#    - org.jboss.tools.project.examples.feature.feature.group
#    - org.jboss.tools.cdi.seam.feature.feature.group
#    - org.jboss.tools.seam.feature.feature.group
#  tags:
#    - wildfly

# GWT

- name: add the GWT plugin
  command: nci install from http://storage.googleapis.com/gwt-eclipse-plugin/v3/release {{ item }}
           chdir=/opt/eclipse/latest
           creates=/opt/eclipse/latest/plugins/com.gwtplugins.*
  with_items:
    - com.gwtplugins.eclipse.sdkbundle.gwt28.feature.feature.group
    - com.gwtplugins.eclipse.suite.v3.feature.feature.group
    - com.github.sdbg.feature.feature.group
  tags:
    - eclipse
    - eclipse-plugin
    - gwt

# Eclim (http://eclim.org)

- name: download Eclim
  uri: url={{ eclim_url }}
       dest=~/{{ eclim_file }}
       creates=~/{{ eclim_file }}
  tags:
    - eclim
    - eclipse
    - vim
  
