---

- name: "install multimedia tools via apt"
  apt:
    pkg:
    - "asciinema"
    - "audacity"
    - "libuvc0"
    - "guvcview"
    - "recordmydesktop"
    - "v4l-utils"
    - "vlc"
  tags:
  - "multimedia"

- name: "install OBS Studio and plugins via flatpak"
  flatpak:
    name: "{{ item }}"
  with_items:
  - "com.obsproject.Studio" # Deb - https://github.com/obsproject/obs-studio/wiki/install-instructions#linux
  - "com.obsproject.Studio.Plugin.BackgroundRemoval" # Deb - https://github.com/obsproject/obs-studio/wiki/install-instructions#linux
  - "io.github.Soundux" # Deb - https://github.com/Soundux/Soundux/releases
  tags:
  - "obs-studio"
  - "multimedia"
