---
# File: roles/cloud/tasks/main.yml

- name: uninstall AWS CLI v1 via PIP
  pip:
    name:
    - awscli
    - awscliv2
    state: absent
  tags:
  - cloud
  - aws

- name: "remove aws symlink"
  file:
    dest: "/usr/local/bin/aws"
    state: "absent"
  tags:
  - cloud
  - aws

- name: "remove aws_completer symlink"
  file:
    dest: "/usr/local/bin/aws_completer"
    state: "absent"
  tags:
  - cloud
  - aws

- name: "remove aws cli"
  file:
    dest: "/usr/local/aws-cli"
    state: "absent"
  tags:
  - cloud
  - aws

- name: "add the Azure CLI signing key"
  get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /etc/apt/trusted.gpg.d/microsoft.asc
  tags:
  - cloud
  - azure

- name: "add the Azure CLI repository"
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main
    state: present
    update_cache: yes
  tags:
  - cloud
  - azure

- name: "install the Azure CLI"
  apt:
    pkg:
    - azure-cli
  tags:
  - cloud
  - azure
