---
# File: roles/cloud/tasks/main.yml

- name: uninstall AWS CLI v1 via PIP
  pip:
    name:
    - awscli
    - awscliv2
    state: absent
  tags:
  - cloud
  - aws

- name: "add a symlink from awsv2 -> aws"
  file:
    dest: "/usr/local/bin/aws"
    state: "absent"
  tags:
  - cloud
  - aws

- name: "download and unarchive AWS CLI tool"
  unarchive:
    src: "{{ awscli_url }}"
    dest: "/tmp"
    remote_src: "yes"
  register: aws_unarchive_result
  tags:
  - cloud
  - aws

- debug:
    msg: "{{ aws_unarchive_result }}"
  tags:
  - aws

- name: "install AWS CLI tool"
  command: "/tmp/aws/install"
  when: aws_unarchive_result is changed
  tags:
  - "cloud"
  - "aws"

- name: install latest Azure CLI tools via SNAP
  snap:
    name: "azure-cli"
    channel: "candidate"
    state: "present"
  when: ansible_distribution == "Ubuntu"
  tags:
    - cloud
    - azure

- name: "add the Azure CLI signing key"
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_distribution == "Debian"
  tags:
  - cloud
  - azure

- name: "add the Azure CLI repository"
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main
    state: present
    update_cache: yes
  when: ansible_distribution == "Debian"
  tags:
  - cloud
  - azure

- name: "install the Azure CLI"
  apt:
    pkg:
    - azure-cli
  when: ansible_distribution == "Debian"
  tags:
  - cloud
  - azure
