---
# File: workstation.yml

- hosts: all
  remote_user: ansible
  become: yes
  vars_files:
    - workstation_versions.yml
  roles:
    - common
    - development
    - containerization
    - java
    - netbeans
    - jmeter
    - zaproxy
    - burp_suite
    - sqlmap
    - findbugs
    - firefox_de
    - google_chrome
    - dbeaver
    - apache_directory_studio
    - eclipse
    - umlet
    - soapui
    - micro
    - pencil
    - postman
    - ratpoison
    - cloud
    - visual_studio
