---
# File: workstation.yml

- hosts: all
  vars_files:
    - workstation_versions.yml
  pre_tasks:
    - name: Fail if Ansible version is too old 
      fail: 
        msg: "Workstation requires a minimum Ansible version of {{ ansible_minimum_version }}. Please update Ansible and run workstation.sh again."
      when: ansible_version.full is version(ansible_minimum_version, operator='lt', strict=True)
  remote_user: ansible
  become: yes
  vars_files:
    - workstation_versions.yml
  roles:
    - platform
    - common
    - development
    - containerization
    - java
    - netbeans
    - jmeter
    - zaproxy
    - burp_suite
    - sqlmap
    - spotbugs
    - firefox_de
    - google_chrome
    - dbeaver
    - apache_directory_studio
    - eclipse
    - umlet
    - soapui
    - micro
    - pencil
    - postman
    - ratpoison
    - cloud
    - visual_studio
