---

- name: "install 1Password desktop client"
  apt:
    deb: "{{ one_password_url }}"
  tags:
  - "1password"
  - "security"

- name: "install keybase"
  apt:
    deb: "{{ keybase_url }}"
  tags:
  - "keybase"
  - "security"
