---
# File: roles/firefox_de/tasks/main.yml

- name: "check to find whether Firefox DE is already installed"
  command: "{{ executable_path }} --version"
  register: firefox_version_result
  failed_when: false
  changed_when: false
  tags:
  - "firefox-de"

- name: "get Firefox DE's redirect link (to parse version)"
  uri:
    url: "{{ latest_url }}"
    method: GET
    follow_redirects: none
    status_code: 302
  register: latest_redirect_result
  tags:
  - "firefox-de"

- name: "extract Firefox DE's version number"
  set_fact:
    latest_version: "{{ latest_redirect_result.location | regex_replace('^.*/releases/', '') | regex_replace('/linux.*$', '') }}"
  tags:
  - "firefox-de"

- name: "download and unarchive Firefox DE"
  unarchive:
    src: "{{ download_url }}"
    remote_src: "yes"
    dest: "{{ destination_directory }}"
  when: firefox_version_result.rc > 0
  tags:
  - "firefox-de"

- name: "move unarchive directory to final location"
  command: "mv {{ destination_directory }}/{{ archive_path }} {{ destination_directory }}/{{ local_path }}"
  when: firefox_version_result.rc > 0
  tags:
  - "firefox-de"

- name: "create a symlink to the executable"
  file:
    src: "{{ executable_path }}"
    dest: "{{ destination_directory }}/{{ executable_name }}"
    state: "link"
  tags:
  - "firefox-de"

- name: "copy Firefox DE's icon in user-space"
  copy:
    src: "{{ icon_path }}"
    dest: "~/.local/share/icons/firefox.png"
    remote_src: yes
  tags:
  - "firefox-de"

- name: "add the Firefox DE desktop file"
  template:
    src: ../templates/firefox-de.desktop
    dest: ~/.local/share/applications
  tags:
  - "firefox-de"
