---

# https://github.com/VSCodium/vscodium/releases/download/1.112.01907/VSCodium-1.112.01907.glibc2.30-x86_64.AppImage
# https://github.com/VSCodium/vscodium/releases/download/1.112.01907/VSCodium-1.112.01907.glibc2.30-x86_64.AppImage.sha256

codium_org: "VSCodium"
codium_repo: "vscodium"
codium_version: "<placeholder>"
codium_file: "VSCodium-{{ codium_version }}.glibc2.34-x86_64.AppImage"

codium_appimage_url: "https://github.com/{{ codium_org }}/{{ codium_repo }}/releases/download/{{ codium_version }}/{{ codium_file }}"
codium_appimage_checksum: "sha256:{{ codium_appimage_url }}.sha256"

# RFC

# https://raw.githubusercontent.com/bfontaine/rfc/v0.2.5/rfc

rfc_host: "https://raw.githubusercontent.com"
rfc_path: "bfontaine/rfc/v{{ rfc_version }}"
rfc_file: "rfc"

rfc_url: "{{ rfc_host }}/{{ rfc_path }}/{{ rfc_file }}"

rfc_installation_directory: "/opt/rfc"
rfc_home_directory: "{{ rfc_installation_directory }}/{{ rfc_version }}"
