---
#

# Make sure we're using a GITHUB_TOKEN for authenticated GitHub acccess

- name: The GITHUB_TOKEN environment variable must be non-empty
  ansible.builtin.assert:
    that:
      - lookup('env', 'GITHUB_TOKEN') | length > 0
  tags:
    - asdf

- name: Check that the GITHUB_TOKEN is authenticated
  ansible.builtin.shell: |
    set -o pipefail
    gh auth status | sed -n -e '/GITHUB_TOKEN/p'
  register: github_auth_status_result
  changed_when: false
  failed_when: '"ailed to log in to github.com using token" in github_auth_status_result.stdout'
  tags:
    - asdf

- name: Install tools via asdf
  ansible.builtin.include_tasks: tools.yaml
  loop: "{{ tools }}"
  loop_control:
    loop_var: tool_item
  tags:
    - asdf
