---
#

- name: install asdf
  git:
    repo: https://github.com/asdf-vm/asdf.git
    dest: ~/.asdf
    version: "{{ asdf_version }}"
    update: no
  tags:
  - asdf

- name: make bash version executable
  file:
    path: ~/.asdf/asdf.sh
    mode: 0500
  tags:
  - asdf

- name: symlink to the asdf bash executable
  file:
    src: ~/.asdf/asdf.sh
    dest: ~/bin/asdf
    mode: 0500
    state: link
  tags:
  - asdf

- name: install asdf and associated completions
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR asdf"
    block: |
      # enable asdf hook and completions
      . ~/.asdf/asdf.sh
      . ~/.asdf/completions/asdf.bash
  tags:
  -  asdf

# TODO: figure out how to make this pretty by adding a newline

- name: install tools via asdf
  include_tasks: tools.yml
  loop: "{{ tools }}"
  loop_control:
    loop_var: tool_item
  tags:
  - asdf

  # TODO: add bash completion for bazel (from install)
  # TODO: add bash completion for go
  # TODO: add bash completions for helm
  # TODO: add bash completion for kind
  # TODO: add bash completion for ko
  # TODO: add bash completion for kubectx
  # TODO: add bash completion for kubens
  # TODO: add bash completion for minikube
  # TODO: add bash completion for terraform

- name: hook direnv into the bash shell
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR direnv"
    block: |
      # hook direnv into the bash shell
      eval "$(direnv hook bash)"
  tags:
  - asdf

- name: add Go programs to path
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK FOR Go programs"
    block: |
      # add Go programs to path
      export PATH=~/go/bin:$PATH
  tags:
  - asdf

- name: remove global tools installed by deprecated Ansible plays
  include_tasks: removes.yml
  args:
    apply:
      become: yes
  loop: "{{ removes }}"
  loop_control:
    loop_var: remove_item
  tags:
  - asdf

- name: remove local tools installed by deprecated Ansible plays
  include_tasks: removes.yml
  loop: "{{ cleans }}"
  loop_control:
    loop_var: remove_item
  tags:
  - asdf
