---

- name: "install communication tools via flatpak"
  flatpak:
    name: "{{ item }}"
  with_items:
  - "com.discordapp.Discord"
  - "com.slack.Slack"
  - "us.zoom.Zoom"
  tags:
  - "communication"
