---

- name: "install Slack"
  apt:
    deb: "{{ item }}"
  with_items:
  - http://ftp.mx.debian.org/debian/pool/main/libi/libindicator/libindicator3-7_0.5.0-3+b1_amd64.deb
  - http://ftp.mx.debian.org/debian/pool/main/liba/libappindicator/libappindicator3-1_0.4.92-7_amd64.deb
  - "{{ slack_url }}"
  when: ansible_distribution == "Debian"
  tags:
  - "slack"
  - "communication"

- name: "install Slack"
  apt:
    deb: "{{ slack_url }}"
  when: ansible_distribution != "Debian"
  tags:
  - "slack"
  - "communication"

- name: "install Zoom"
  apt:
    deb: "{{ zoom_url }}"
  tags:
  - "zoom"
  - "communication"
