---

- name: install selected codium extensions
  command:
    # cmd: "codium --install-extension {{ item }} --user-data-dir /usr/share/code --force"
    cmd: "/usr/bin/flatpak run --branch=stable --arch=x86_64 --file-forwarding --session-bus com.vscodium.codium --install-extension {{ item }} --force"
  with_items: "{{ codium_extensions }}"
  register: codium_extension
  changed_when: "'already installed' not in codium_extension.stdout"
  tags:
    - "vscodium"
    - "ide"
    - "development"

- name: "update installed codium extensions"
  command:
    cmd: "/usr/bin/flatpak run --branch=stable --arch=x86_64 --file-forwarding --session-bus com.vscodium.codium --update-extensions --force"
  register: update_codium_extensions_result
  changed_when: "update_codium_extensions_result.stdout != 'No extension to update'"
  tags:
    - "vscodium"
    - "ide"
    - "development"
