---
# File: roles/development/tasks/main.yml

- name: "Install development tools via apt"
  apt:
    pkg:
      - "ansible-lint"
  tags:
    - "development"

- name: "Install development tools via flatpak"
  community.general.flatpak:
    name: "{{ item }}"
  with_items:
    - "com.vscodium.codium"
    - "rest.insomnia.Insomnia"
  tags:
    - "codium"
    - "insomnia"
    - "rest"
    - "development"

# #
# # Editors
# #

- name: "add the full-featured versions of vim"
  apt:
    name: "{{ packages }}"
    state: "present"
  vars:
    packages:
    - "vim"
    - "vim-gtk3"
  tags:
    - "editors"
    - "vim"

# #
# # Virtualization
# #

- name: "install fasttrack repo key (Debian)"
  apt:
    pkg:
    - "fasttrack-archive-keyring"
    state: "present"
  when: ansible_distribution == "Debian"
  tags:
  - "virtualbox"
  - "virtualization"

- name: "install fastrack repo (Debian)"
  ansible.builtin.deb822_repository:
    name: debian-fasttrack
    types: deb
    uris: https://fasttrack.debian.net/debian-fasttrack/
    suites: "{{ ansible_distribution_release }}-fasttrack"
    components: "main contrib"
    state: "present"
  when: ansible_distribution == "Debian"
  tags:
  - "virtualbox"
  - "virtualization"

- name: "install staging repo (Debian)"
  ansible.builtin.deb822_repository:
    name: debian-fasttrack-staging
    types: deb
    uris: https://fasttrack.debian.net/debian-fasttrack/
    suites: "{{ ansible_distribution_release }}-backports-staging"
    components: "main contrib"
    state: "present"
  when: ansible_distribution == "Debian"
  tags:
  - "virtualbox"
  - "virtualization"

- name: "install virtualbox (Debian or Ubuntu)"
  apt:
    pkg:
    - "virtualbox"
    - "virtualbox-qt"
    state: "present"
  tags:
  - "virtualbox"
  - "virtualization"

# #
# # LDAP tools
# #

- name: "install linux tools for LDAP"
  apt:
    name: "{{ packages }}"
    state: "latest"
  vars:
    packages:
    - "ldap-utils"
    - "ldapvi"
  tags:
    - "ldap"

# #
# # Networking
# #

- name: "add packages that are useful when developing networking software"
  apt:
    name: "{{ packages }}"
    state: "latest"
  vars:
    packages:
    - "wireshark"
    - "nmap"
    - "nmapsi4"
  tags:
    - "networking"

# #
# # Graphics
# #

# #
# # Inform
# #

# - name: "add packages needed to develop IF games"
#   apt:
#     pkg:
#     - "inform"
#     - "inform-docs"
#     state: "latest"
#   vars:
#     packages:
#   when: ansible_distribution != "Debian"
#   tags:
#     - "interactive-fiction"
#     - "inform"

# - name: "add stretch repositories needed for Inform7 dependencies"
#   apt_repository:
#     repo: "{{ item }}"
#     state: present
#     update_cache: yes
#   with_items:
#   - "deb http://deb.debian.org/debian stretch main"
#   - "deb-src http://deb.debian.org/debian stretch main"
#   when: ansible_distribution == "Debian"
#   tags:
#   - "interactive-fiction"
#   - "inform"

# - name: "add old dependencies needed for Inform7"
#   apt:
#     pkg:
#     - libgoocanvas3
#     - libgtkspell0
#     - libjavascriptcoregtk-1.0-0
#     - libwebkitgtk-1.0-0
#     - libgtksourceview2.0-0
#     state: present
#   when: ansible_distribution == "Debian"
#   tags:
#   - "interactive-fiction"
#   - "inform"

# - name: "install Inform7"
#   apt:
#     deb: http://inform7.com/apps/6M62/gnome-inform7_6M62-1_amd64.deb
#     state: "present"
#   when: ansible_distribution == "Debian"
#   tags:
#     - "interactive-fiction"
#     - "inform"

# - name: "remove stretch repositories needed for Inform7 dependencies"
#   apt_repository:
#     repo: "{{ item }}"
#     state: absent
#     update_cache: yes
#   with_items:
#   - "deb http://deb.debian.org/debian stretch main"
#   - "deb-src http://deb.debian.org/debian stretch main"
#   when: ansible_distribution == "Debian"
#   tags:
#   - "interactive-fiction"
#   - "inform"

# - name: "add packages needed to play IF games"
#   apt:
#     pkg:
#     - "frotz"
#     - "zoom-player"
#     state: "latest"
#   tags:
#     - "interactive-fiction"

# # RFC CLI browser

# - name: "create the home directory for the RFC browser"
#   file:
#     name: "{{ rfc_home_directory }}"
#     state: "directory"
#   tags:
#   - rfc

# - name: "install the RFC browser"
#   get_url:
#     url: "{{ rfc_url }}"
#     dest: "{{ rfc_home_directory }}"
#     mode: "755"
#   tags:
#   - rfc

# - name: "create a pretty symlink to the latest version of the RFC browser"
#   file:
#     src: "{{ rfc_home_directory }}"
#     dest: "{{ rfc_installation_directory }}/latest"
#     state: "link"
#   tags:
#   - "rfc"

# - name: "create a symlink to the RFC browser executable"
#   file:
#     src: "{{ rfc_installation_directory }}/latest/{{ rfc_file }}"
#     dest: "/usr/bin/{{ rfc_file }}"
#     state: "link"
#   tags:
#   - "rfc"

# #
# # Test tools
# #

# - name: "install siege for HTTP load testing"
#   apt:
#     pkg:
#     - "siege"
#     state: "latest"
#   tags:
#   - "testing"
#   - "siege"
