---
# File: roles/java/tasks/main.yml

#
# OpenJDK
#
  
- name: remove the legacy OpenJDK JRE"
  apt:
    name: openjdk-{{ java_legacy_version }}-jre
    state: absent
    autoremove: yes
  tags:
    - java
    - clean-legacy
  
- name: clean the legacy OpenJDK packages"
  apt:
    name: openjdk*
    state: absent
    purge: yes
  tags:
    - java
    - clean-legacy
