---
# File: roles/firefox_de/vars/main.yml
# https://download-installer.cdn.mozilla.net/pub/devedition/releases/55.0b2/linux-x86_64/en-US/firefox-55.0b2.tar.bz2
# https://download-installer.cdn.mozilla.net/pub/devedition/releases/55.0b3/linux-x86_64/en-US/firefox-55.0b3.tar.bz2
# https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US

key: "firefox-de"
title: "Firefox Developer Edition"
version: "{{ firefox_de_version }}"

host: "https://download-installer.cdn.mozilla.net"
path: "pub/devedition/releases/{{ firefox_de_version }}/linux-x86_64/en-US"
file: "firefox-{{ firefox_de_version }}.tar.bz2"

url: "{{ host }}/{{ path }}/{{ file }}"

archive_path: "firefox"

executables: []

desktop_file: "firefox-de.desktop"
