---
# File: roles/firefox_de/vars/main.yml

# This URL:
# https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US
# redirects to something like this (with a different version)
# https://download-installer.cdn.mozilla.net/pub/devedition/releases/128.0b9/linux-x86_64/en-US/firefox-128.0b9.tar.bz2

latest_url: "https://download.mozilla.org/?product=firefox-devedition-latest-ssl&os=linux64&lang=en-US"

host: "https://download-installer.cdn.mozilla.net"
path: "pub/devedition/releases/{{ latest_version }}/linux-x86_64/en-US"
file: firefox-{{ latest_version }}.tar.bz2

download_url: "{{ host }}/{{ path }}/{{ file }}"

destination_directory: "~/bin"
archive_path: "firefox"
local_path: "firefox-de"
executable_name: "firefox"

executable_path: "{{ destination_directory }}/{{ local_path }}/{{ executable_name }}"
icon_path: "{{ destination_directory }}/{{ local_path }}/browser/chrome/icons/default/default48.png"
