---

- name: "make the installation directory"
  file:
    path: "{{ terragrunt_home_directory }}"
    state: directory
  tags:
  - terragrunt
  - iac

- name: "download terragrunt executable"
  get_url:
    url: "{{ terragrunt_url }}"
    dest: "{{ terragrunt_home_directory }}"
    mode: 0755
  tags:
  - terragrunt
  - iac

- name: "link latest to the new version"
  file:
    path: "{{ terragrunt_installation_directory }}/latest"
    src: "{{ terragrunt_home_directory }}"
    state: link
  tags:
  - terragrunt
  - iac

- name: "link to bin"
  file:
    path: "/usr/bin/terragrunt"
    src: "{{ terragrunt_installation_directory }}/latest/{{ terragrunt_file }}"
    state: link
  tags:
  - terragrunt
  - iac
