---

# Ollama should probably be installed on the host instead of running within
# FlatPak as a sub-servrice of Alpaca.  See the instructions at
#    https://github.com/ollama/ollama/blob/main/docs/linux.md
# And the command that's recommended is:
#    curl -fsSL https://ollama.com/install.sh | sh

- name: "install Alpaca (and managed Ollama) via flathub"
  flatpak:
    name: "{{ item }}"
  with_items:
    - "com.jeffser.Alpaca"
    - "com.jeffser.Alpaca.Plugins.Ollama"
  tags:
  - "ai"