---
# File: roles/containerization/tasks/main.yml

#
# Podman
#

- name: "Install podman and tools for container execution environment"
  ansible.builtin.apt:
    pkg:
      - "podman"
      - "podman-compose"
      - "podman-docker"
      - "podman-toolbox"
  tags:
    - "podman"
    - "containerization"

- name: "Install podman-desktop via flatpak"
  community.general.flatpak:
    name: "io.podman_desktop.PodmanDesktop" # https://appimage.github.io/Podman/
  tags:
    - "podman"
    - "containerization"
