---
# File: roles/containerization/tasks/main.yml

#
# Podman
#

- name: install podman and tools for container execution environment
  apt:
    pkg:
      - podman
      - podman-compose
      - podman-docker
      - podman-toolbox
    state: latest
  tags:
    - containerization
    - podman
