---
# Remove f.lux (see https://justgetflux.com/linux.html) if installed
- name: remove f.lux
  apt:
    name: fluxgui
    state: absent
  register: fluxgui_was_installed
  tags:
    - ergonomics

- name: remove legacy f.lux repository file
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/nathan-renniewaldock-ubuntu-flux-{{ ansible_distribution_release }}.list"
    state: absent
  tags:
    - ergonomics

- name: remove legacy f.lux repository source file
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/nathan-renniewaldock-ubuntu-flux-{{ ansible_distribution_release }}-source.list"
    state: absent
  tags:
    - ergonomics

- name: "remove Obsidian previously installed via flatpak"
  flatpak:
    name: "md.obsidian.Obsidian"
    state: "absent"
  tags:
  - "obsidian"
  - "productivity"

