---
# Remove f.lux (see https://justgetflux.com/linux.html) if installed
- name: remove f.lux
  apt:
    name: fluxgui
    state: absent
  register: fluxgui_was_installed
  tags:
    - ergonomics

- name: remove the f.lux repository
  apt_repository:
    repo: "deb http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu bionic main"
    state: absent
  when: fluxgui_was_installed is changed
  tags:
    - ergonomics

- name: remove the f.lux source repository
  apt_repository:
    repo: "deb-src http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu bionic main"
    state: absent
  when: fluxgui_was_installed is changed
  tags:
    - ergonomics

- name: remove the f.lux signing key
  apt_key:
    keyserver: keyserver.ubuntu.com id=428926204FE30238F00B98224CDB129629A4B41A
    state: absent
  when: fluxgui_was_installed is changed
  tags:
    - ergonomics
