---

- name: "Create a folder for AppImage applications"
  ansible.builtin.file:
    path: "{{ user_appimage_directory }}"
    state: directory
  tags:
    - "appimage"

- name: "install Obsidian as AppImage"
  ansible.builtin.get_url:
    url: "{{ obsidian_appimage_url }}"
    dest: "{{ user_appimage_directory }}"
  tags:
    - "obsidian"
    - "appimage"

- name: "make the Obsidian AppImage executable"
  ansible.builtin.file:
    path: "{{ user_appimage_directory }}/Obsidian-1.12.7.AppImage"
    mode: "0755"
  tags:
    - "obsidian"
    - "productivity"
    - "office"
    - "appimage"
