---
# File: roles/containerization/vars/main.yml

#
# Kubernetes
#

# This is still needed solely to delete previous workstation installs of Kubernetes
k8s_name: kubernetes
k8s_installation_directory: /opt/{{ k8s_name }}

# https://github.com/GoogleContainerTools/skaffold/releases/download/v1.16.0/skaffold-linux-amd64

skaffold_host: "https://github.com"
skaffold_path: "GoogleContainerTools/skaffold/releases/download/v{{ skaffold_version }}"
skaffold_file: "skaffold-linux-amd64"

skaffold_url: "{{ skaffold_host }}/{{ skaffold_path }}/{{ skaffold_file }}"

skaffold_installation_directory: "/opt/skaffold"
skaffold_home_directory: "{{ skaffold_installation_directory }}/{{ skaffold_version }}"

# https://lens-binaries.s3-eu-west-1.amazonaws.com/ide/Lens-5.4.6-latest.20220428.1.amd64.deb
# https://downloads.k8slens.dev/ide/Lens-5.5.4-latest.20220609.2.amd64.deb

lens_url: https://downloads.k8slens.dev/ide/Lens-{{ lens_version }}.amd64.deb
