---

# asdf - the multiple runtime version manager

- name: "get latest asdf release information"
  community.general.github_release:
    user: "asdf-vm"
    repo: "asdf"
    action: "latest_release"
  register: "release_asdf_result"
  tags:
  - "asdf"
  - "packaging"
  - "setup"
  
- ansible.builtin.debug:
    msg: "{{ release_asdf_result.tag }}"
  tags:
  - "asdf"
  - "packaging"
  - "setup"

- name: "save asdf version"
  ansible.builtin.set_fact:
    asdf_version: "{{ release_asdf_result.tag }}"
  tags:
  - "asdf"
  - "packaging"
  - "setup"

- name: "unarchive latest release file"
  ansible.builtin.unarchive:
    src: "{{ asdf_archive_url }}"
    dest: "~/bin"
    remote_src: yes
  tags:
  - "asdf"
  - "packaging"
  - "setup"
