---

# asdf - the multiple runtime version manager

- name: "install asdf"
  git:
    repo: "https://github.com/asdf-vm/asdf.git"
    dest: "~/.asdf"
    # version: "{{ asdf_version }}"
    version: "v0.12.0"
    update: no
  register: "install_asdf_result"
  tags:
  - "asdf"
  - "packaging"
  - "setup"

# No longer supported
# - name: "update asdf to the latest version"
#   command: "~/.asdf/bin/asdf update"
#   register: "asdf_update_result"
#   changed_when: "'Previous HEAD position was' in asdf_update_result.stderr"
#   tags:
#   - "asdf"
#   - "packaging"
#   - "setup"
