---

# apt - native Debian package manager

- name: "upgrade existing apt packages"
  apt:
    upgrade: "yes"
    update_cache: "yes"
    autoclean: "yes"
    autoremove: "yes"
    state: "latest"
  tags:
  - "packaging"
  - "setup"

# pip/pipx - install Python3 libraries and commands

- name: "add the PIP package manager"
  apt:
    pkg:
    - "python3-setuptools"
    - "python3-pip"
    - "python3-virtualenv"
    - "pipx"
  tags:
    - "python"
    - "packaging"
    - "setup"

# flatpak - encapsulated applications with (optional) sandboxing

- name: "add the flatpak package manager"
  apt:
    pkg:
    - "flatpak"
  tags:
  - "flatpak"
  - "packaging"
  - "setup"

- name: "add the flathub remote repository"
  flatpak_remote:
    name: "flathub"
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
  tags:
  - "flatpak"
  - "packaging"
  - "setup"

- name: "upgrade existing flatpak applications"
  command: "flatpak update --noninteractive"
  register: "update_flatpak_apps_result"
  changed_when: "'Nothing to do.' not in update_flatpak_apps_result.stdout"
  tags:
  - "flatpak"
  - "packaging"
  - "setup"

# appimagelauncher - install daemon and desktop integration

- name: "install appimagelauncher"
  apt:
    pkg: "appimagelauncher"
  tags:
  - "appimagelauncher"
  - "packaging"
  - "setup"
