---

# apt - native Debian package manager

- name: "add trixie backports repository"
  deb822_repository:
    name: debian
    types: deb
    uris: http://deb.debian.org/debian
    suites: trixie
    components:
      - backports
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_major_version == "13"
  tags:
  - "packaging"
  - "setup"

- name: "upgrade existing apt packages"
  apt:
    upgrade: "yes"
    update_cache: "yes"
    autoclean: "yes"
    autoremove: "yes"
    state: "latest"
  tags:
  - "packaging"
  - "setup"

# pip/pipx - install Python3 libraries and commands

- name: "add the PIP package manager"
  apt:
    pkg:
    - "python3-setuptools"
    - "python3-pip"
    - "python3-virtualenv"
    - "pipx"
  tags:
    - "python"
    - "packaging"
    - "setup"

- name: "install github3.py in system venv"
  ansible.builtin.pip:
    name: "github3.py"
    break_system_packages: true
  tags:
    - "python"
    - "packaging"
    - "setup"

# flatpak - encapsulated applications with (optional) sandboxing

- name: "add the flatpak package manager"
  apt:
    pkg:
    - "flatpak"
  tags:
  - "flatpak"
  - "packaging"
  - "setup"

- name: "add the flathub remote repository"
  flatpak_remote:
    name: "flathub"
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
  tags:
  - "flatpak"
  - "packaging"
  - "setup"

- name: "upgrade existing flatpak applications"
  command: "flatpak update --noninteractive"
  register: "update_flatpak_apps_result"
  changed_when: "'Nothing to do.' not in update_flatpak_apps_result.stdout"
  tags:
  - "flatpak"
  - "packaging"
  - "setup"

- name: "install flatseal to manage flatpak sandbox permissions"
  community.general.flatpak:
    name: "com.github.tchx84.Flatseal" # Not needed?
  tags:
  - "flatpak"
  - "packaging"
  - "setup"

# appimagelauncher - install daemon and desktop integration

- name: "determine the correct FUSE package name"
  set_fact:
    fuse_package: "{{ fuse_map[ansible_distribution_major_version] | default('libfuse2') }}"
  vars:
    fuse_map:
      "12": "libfuse2"
      "13": "libfuse2t64"
  tags:
  - "appimage"
  - "packaging"
  - "setup"

- name: "install userspace FUSE"
  apt:
    pkg:
      # - "{{ appimage_launcher_deb_url }}"
      - "{{ fuse_package }}"
  tags:
  - "appimage"
  - "packaging"
  - "setup"

- name: "install appimagelauncher"
  apt:
    deb: "{{ appimage_launcher_deb_url }}"
  tags:
  - "appimage"
  - "packaging"
  - "setup"

# Install DBUS messaging for X11 applications

- name: "install DBUS messaging"
  apt:
    pkg:
    - "dbus-x11"
  tags:
  - "setup"

# NodeJS and NPM from NodeSource

# - name: "add the NodeDource signing key"
#   ansible.builtin.get_url:
#     url: "{{ nodesource_apt_key_url }}"
#     dest: "{{ nodesource_apt_key_tmp_file }}"
#   tags:
#   - "node"
#   - "setup"

# - name: add NodeDource signing key to keyring
#   ansible.builtin.apt_key:
#     id: "{{ nodesource_apt_key_id }}"
#     file: "{{ nodesource_apt_key_tmp_file }}"
#     state: present
#   tags:
#   - "node"
#   - "setup"

# - name: add NodeSource apt repository into sources list
#   ansible.builtin.apt_repository:
#     repo: "{{ nodesource_apt_repo }}"
#     state: present
#     filename: "{{ nodesource_apt_repo_src_file }}"
#   tags:
#   - "node"
#   - "setup"

# - name: add nodejs and npm
#   ansible.builtin.apt:
#     pkg:
#     - nodejs
#     - npm
#     state: present
#   tags:
#   - "node"
#   - "setup"

      # Nodejs Config
    # echo "Package: nodejs" | tee /etc/apt/preferences.d/nodejs > /dev/null
    # echo "Pin: origin deb.nodesource.com" | tee -a /etc/apt/preferences.d/nodejs > /dev/null
    # echo "Pin-Priority: 600" | tee -a /etc/apt/preferences.d/nodejs > /dev/null