---

- name: "upgrade existing apt packages"
  apt:
    upgrade: "yes"
    update_cache: "yes"
    autoclean: "yes"
    autoremove: "yes"
    state: "latest"

- name: "add the PIP package manager"
  apt:
    pkg:
    - "python3-setuptools"
    - "python3-pip"
  tags:
    - "python"
    - "packaging"

- name: "add the flatpak package manager"
  apt:
    pkg:
    - "flatpak"
  tags:
  - "flatpak"
  - "packaging"

- name: "add the flathub remote repository"
  flatpak_remote:
    name: "flathub"
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"
  tags:
  - "flatpak"
  - "packaging"

- name: "upgrade existing flatpak applications"
  command: "flatpak update --noninteractive"
  register: update_flatpak_apps_result
  changed_when: "'Nothing to do.' not in update_flatpak_apps_result.stdout"
  tags:
  - "flatpak"
  - "packaging"
