---

user_appimage_directory: "~/Applications"

obsidian_version: "<placeholder>"
obsidian_appimage_url: "https://github.com/obsidianmd/obsidian-releases/releases/download/v{{ obsidian_version }}/Obsidian-{{ obsidian_version }}.AppImage"
